name: Build and Push Docker Image
on:
  release:
    types: [published] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build . -t gobetti/cesilab:${{ github.ref_name }}

      - name: Push Docker Image
        run: docker push gobetti/cesilab:${{ github.ref_name }}
