name: Build and Push Docker Image
on:
  release:
    types: [published] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest   
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get release tag
        run: |
          echo Release tag found : ${{ github.event.release.tag_name }}
          
      # - name: Modify version.js
      #   uses: jaywcjlove/github-action-modify-file-content@main
      #   with:
      #     branch: main
      #     path: docu-form/src/version.js
      #     body: "const app_version = '${{ github.event.release.tag_name }}'; export default app_version;"
      #     overwrite: 'true'

      - name: Build Docker Image
        working-directory: docu-form
        run: docker build . -t gobetti/cesilab:${{ github.event.release.tag_name }}

      - name: Push Docker Image
        working-directory: docu-form
        run: docker push gobetti/cesilab:${{ github.event.release.tag_name }}
